kurento:
  __name: KURENTO
  __format: json

redisHost: REDIS_HOST
mcs-port: MCS_PORT
mcs-address: MCS_HOST

freeswitch:
    ip: FREESWITCH_IP
    esl_ip: ESL_IP
    esl_port: ESL_PORT

log:
    level: LOG_LEVEL

bbb-stream:
    image_name: STREAM_IMAGE_NAME
    bigbluebutton_url: STREAM_BIGBLUEBUTTON_URL
    bigbluebutton_secret: STREAM_BIGBLUEBUTTON_SECRET
    container_type: STREAM_CONTAINER_TYPE
    bot_name: STREAM_BOT_NAME

rnp:
  oauth2:
    client_id: VIDEO_RNP_CLIENT_ID
    client_secret: VIDEO_RNP_CLIENT_SECRET
    redirect_uri: VIDEO_RNP_REDIRECT_URI
    host_ip: VIDEO_RNP_HOST_IP

recordWebcams: RECORD_WEBCAMS
recordScreenSharing: RECORD_SCREENSHARE

processes:
  __name: SFU_PROCESSES
  __format: json
